sei: # 应用全局配置
  application:
    code: sei-manager
    name: SEI开发运维平台
    env: DEV
    swagger:
      title: "${sei.application.name} API"
      description: "${sei.application.name} 的API文档，运行环境: ${sei.application.env}"
      version: ${sei.application.version}
  # 日志配置,不使用kafka日志
  log:
    kafka:
      enable: false
  monitor:
    websocket:
      enable: false
  jenkins:
    host: 'http://10.4.208.130:8088'
    username: 'hua.feng'
    password: 'fenghua1'
  gitlab:
    host: 'http://rddgit.changhong.com'
    token: 'n_DEjjbZxTrSWNf-SKsV'
  # nodejs 服务地址
  node-server: 'http://10.4.208.130:7001'
  build:
    # web hook方式构建开发环境
    hook: true
    # 定时任务方式构建开发环境
    timing: false
  # 开发运维平台的服务端地址(若有代理,配置代理后的地址)
  server:
    host: 'http://dsei.changhong.com/sei-manager'
    web: 'http://dsei.changhong.com/sei-manager-web'
  # 支持的邮箱服务(账号注册时用)
  email:
    servers: '@changhong.com, @qq.com'


spring:
  application:
    name: ${sei.application.code}
  cloud:
    config:
      enabled: false
      #当前环境
      profile: ${sei.application.env}
      name: ${spring.application.name}
  # mail config
  mail:
    password: 1plmjvCR
    protocol: smtp
    port: 25
    host: 10.3.15.240
    properties:
      mail:
        smtp:
          writetimeout: 5000
          starttls:
            enable: true
          auth: true
          connectiontimeout: 5000
          ssl:
            trust: 10.3.15.240
          timeout: 5000
    username: seiadmin@changhong.com

  datasource:
#    username: sei
    username: root
#    password: 123456
    password: 5o1BbPJqedZgNSinMiPU
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://10.4.208.134:3306/sei_manager?characterEncoding=utf8&useSSL=false&useCompression=true&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://10.4.208.68:3366/sei_manager?characterEncoding=utf8&useSSL=false&useCompression=true&serverTimezone=Asia/Shanghai
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      namingStrategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
  # redis config
  redis:
    password: ZmkDbgaua3Rso33T
    database: 0
    port: 6379
    host: 10.4.208.132

# log config
logging:
  level:
    root: WARN
